package com.rest.eskaysoftAPI.entity;

public enum  RoleName {
    ROLE_USER,
    ROLE_ADMIN,
    ALLOW_MASTERS,
    ALLOW_PURCHASE,
    ALLOW_SALES,
    ALLOW_INVENTORY_REPORTS,
    ALLOW_GST_REPORTS,
    ALLOW_MISCELLANEOUS,
    ALLOW_INVOICE_DATE_CHANGE,
    ALLOW_MODIFICATION_OR_DELETION
}
